# Generated by Django 4.0.4 on 2022-06-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('profile_image', models.CharField(max_length=45)),
                ('profile_description', models.TextField()),
                ('host_point', models.IntegerField()),
                ('guest_point', models.IntegerField()),
            ],
        ),
    ]
